### PR TITLE
Added Elixir, Java & Python implementations

### PR DESCRIPTION
**Pull request by ukchukx**
I added implementations of the algorithm for Elixir, Java & Python.
Please merge if you find it useful.

### CODE REVIEW

**Review by mojoblanco — APPROVED** [review]

**Comment by mojoblanco** [comment]
Nice work! I've added a suffix of '_1' to your python implementation to avoid conflicts

**Comment by LordRahl90** [comment]
@ukchukx Nice work, but why r u not iterating the array once u have converted it to array, instead of having to type manually, is there any performance advantage?

**Comment by mojoblanco** [comment]
@LordRahl90 Nice observation.
If you feel there is a better or another way, you are free to make a PR also.

**Comment by ukchukx** [comment]
@LordRahl90 I didn't test the magnitude of whatever performance advantage there might be.
I chose that way because:
- The array size is fixed & small enough that not using a loop would not be too inconvenient.
- If I used a loop, there would have to be a conditional to decide when to multiply by 3 or 7.
```
int sum = 0;
for (int d = 0; d < 12; ++d) {
  sum += accountNumberDigits[d] * ((d % 3 == 1)? 7 : 3); // how I usually use conditionals
  // You could use a good old if-else
  /*
  if (d % 3 == 1) {
    sum += accountNumberDigits[d] * 7;
  } else {
    sum += accountNumberDigits[d] * 3;
  }
  */
}
```
- If I wanted to forgo the use of a conditional, I would have to store the 3's & 7's in another  array.
```
int[] multipliers = new int[3]{3, 7, 3}, // Since this repeats, we can get by without using a 12-element array
int sum = 0;
for (int d = 0; d < 12; ++d) {
  sum += accountNumberDigits[d] * multipliers[d % 3];
}
```
- I could see no good reason for the loop overhead. I just needed to do addition & multiplication on a small array.
- I just do these things by habit.

Note: I could very well be wrong, but these are my reasons.

**Comment by LordRahl90** [comment]
@ukchukx thats a very great insight, what i was thinking is keep the entire length of the 3's and 7's in an array. like so:
`int[] multipliers=new int[12]={3,7,3,3,7,3,3,7,3,3,7,3};`
then we can do something like 
`for(int i=0; i<multipliers.length; i++){
sum+=(multipliers[i])*(accountNumberDigits[i]);
}`
This can now remove the overhead of detecting the 7's and 3's.
or what do u feel???

**Comment by ukchukx** [comment]
@LordRahl90 That's how I would do it if the numbers were not repeating or had no visible relationship.

**Pull request merged**
